version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4566:4566' # Default port for LocalStack
    environment:
      - AWS_DEFAULT_REGION=eu-central-2
      - EDGE_PORT=4566
      - SERVICES=dynamodb,s3,lambda
      - DEBUG=1 # Enable debugging output
      - KINESIS_PROVIDER=kinesalite
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - './:/docker-entrypoint-initaws.d' # Mount your project directory to automatically run scripts
      - '/var/run/docker.sock:/var/run/docker.sock' # Mount the Docker socket to allow LocalStack to manage Docker containers
    networks:
      - backend

  post-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - amazon.dynamodb.endpoint=http://localstack:4566/
      - amazon.aws.accesskey=key
      - amazon.aws.secretkey=key2
    networks:
      - backend
    depends_on:
      - localstack

networks:
  backend:
